version: "3"
services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./html:/usr/share/nginx/html
      - ./php_config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php_config/docoker-fpm.ini:/usr/local/etc/php/conf.d/docoker-fpm.ini
      - ./app:/app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/fastcgi_params:/etc/nginx/fastcgi_params
      - ./html:/usr/share/nginx/html
    restart: always
    ports: ["8081:80"]
    depends_on: ["php"]

  composer:
    image: composer
    volumes:
      - ./app:/app
    links:
      - php
    command: "composer install --optimize-autoloader --no-dev"
